---
title: "Data Preprocessing EDA"
author: "Shivani Vogiral, Ajinkya Pawale, Sharanbasav Sumbad, Anuhya Sankranti"
date: "11/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(rio)
library(ggplot2)
library(broom)
library(grid)
library(mgcv)
library(jpeg)
library(RCurl)
library(GGally)
library(data.table)
```

```{r}
data = read.csv('Chicago_Crime-2019-2021.csv')
```

```{r}
data_2019 = filter(data, year_x == "2019")
```




```{r}
drop = c("date_y", "primary_type_y", "description_y", "location_description_y", "arrest_y", "domestic_y", "year_y", "updated_on_y", "location_y")
data_2019 = data_2019[,!(names(data_2019) %in% drop)]
```

```{r}
summary(data_2019)
```

Distribution of different types of crimes - BAR PLOT
```{r}
ggplot(data_2019, aes(y = primary_type_x)) +
  geom_bar()

crimes = data_2019$primary_type_x
crimes = as.data.frame(table(crimes))
crimes = crimes[order(crimes$Freq,decreasing = TRUE),]
crimes = crimes[crimes$Freq > 5000,]
```



Different location of crimes - BAR PLOT
```{r}
locations = data_2019$location_description_x
locations = as.data.frame(table(locations))
locations = locations[order(locations$Freq,decreasing = TRUE),]
locations = locations[1:9,]
ggplot(locations, aes(y = Freq, x = locations))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
data_2019 = data_2019[data_2019$location_description_x %in% locations$locations,]
data_2019 = data_2019[data_2019$primary_type_x %in% crimes$crimes,]
```

```{r}
data_2019$Date = as.Date(data_2019$date_x)
data_2019$Time <- format(as.POSIXct(data_2019$date_x), format = "%H:%M:%S")
data_2019$Month_num<- strftime(data_2019$date_x, "%m")
```

```{r}
ggplot(data_2019,aes(x = primary_type_x))+
  geom_bar()+
  facet_wrap(~ location_description_x)+
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
data_2019 = data_2019 %>% mutate(location_description_num=recode(location_description_x, 'ALLEY' = 1, 'RESTAURANT' = 2,'SMALL RETAIL STORE'=3,'PARKING LOT/GARAGE(NON.RESID.)'=4,'OTHER'=5,'SIDEWALK'=6,'APARTMENT'=7,'RESIDENCE'=8,'STREET'=9,.default=0))
```

```{r}
data_2019 = data_2019 %>% mutate(primary_type_num=recode(primary_type_x, 'THEFT' = 12, 'BATTERY' = 11,'CRIMINAL DAMAGE'=10,'ASSAULT'=9,'DECEPTIVE PRACTICE'=8,'OTHER OFFENSE'=7,'NARCOTICS'=6,'BURGLARY'=5,'MOTOR VEHICLE THEFT'=4,'ROBBERY'=3,'CRIMINAL TRESPASS'=2,'WEAPONS VIOLATION'=1))
```

```{r}
data_2019$Month = as.numeric(data_2019$Month )
```


```{r}
data_2019$Month_Name = month.name[data_2019$Month]
all(data_2019$Month_Name %in% month.name)
data_2019$Month_Name <- factor(data_2019$Month_Name, levels=month.name)
```



```{r}
data_2019$arrest_num[data_2019$arrest_x == 'True'] = 1
data_2019$arrest_num[data_2019$arrest_x == 'False'] = 0
```

```{r}
data_2019$domestic_num[data_2019$domestic_x == 'True'] = 1
data_2019$domestic_num[data_2019$domestic_x == 'False'] = 0
```

```{r}
data_2019 <- subset( data_2019, select = -c(Time, description_x) )
```


```{r}
data_2019$day <- weekdays(as.Date(data_2019$Date))
```


```{r}
data_2019$location_x = gsub("[()]", "", data_2019$location_x)
data_2019 = separate(data = data_2019, col = location_x, into = c("x_coord", "y_coord"), sep = "\\,")
data_2019$x_coord = as.numeric(data_2019$x_coord)
data_2019$y_coord = as.numeric(data_2019$y_coord)
data_2019 = drop_na(data_2019)
```


```{r}
data_2019 = data_2019 %>% mutate(day_num=recode(day, 'Monday' = 1, 'Tuesday' = 2,'Wednesday'=3,'Thursday'=4,'Friday'=5,'Saturday'=6,'Sunday'=7))
```


```{r}
write.csv(data_2019,'crimes_data_2019.csv')
```

